 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: personalexpensetracker
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: personalexpensetracker
   template:
     metadata:
       labels:
         app: personalexpensetracker
     spec:
       containers:
       - name: personalexpensetracker
         image: uk.icr.io/expensetracker/personalexpensetracker:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 5000